import {
  Anchor,
  Award,
  Backpack,
  Baby,
  BedDouble,
  Bike,
  Bird,
  BookOpen,
  Briefcase,
  Brush,
  Bus,
  Cake,
  Calculator,
  Camera,
  Car,
  Cat,
  Church,
  Clapperboard,
  Compass,
  Cookie,
  Croissant,
  Crown,
  Dices,
  Dog,
  Drama,
  Drum,
  Dumbbell,
  Fish,
  Flag,
  Flame,
  Flower2,
  Footprints,
  Gamepad2,
  Gift,
  Glasses,
  Globe,
  GraduationCap,
  Guitar,
  Hammer,
  HandHeart,
  Headphones,
  Heart,
  HeartPulse,
  Home,
  IceCreamCone,
  Key,
  Landmark,
  Laptop,
  Leaf,
  Library,
  Lightbulb,
  Luggage,
  MapPin,
  Medal,
  Mic,
  Microscope,
  Moon,
  Mountain,
  Music,
  Music2,
  Newspaper,
  Palette,
  Palmtree,
  Paperclip,
  PartyPopper,
  PawPrint,
  Pencil,
  PersonStanding,
  Piano,
  PiggyBank,
  Pill,
  Pizza,
  Plane,
  Popcorn,
  Puzzle,
  Rabbit,
  Rocket,
  Sailboat,
  Scissors,
  School,
  ShoppingBag,
  ShoppingCart,
  Smile,
  Snowflake,
  Sparkles,
  Star,
  Stethoscope,
  Sun,
  Sunrise,
  Syringe,
  Target,
  Tent,
  Theater,
  Ticket,
  Train,
  Trees,
  Trophy,
  Umbrella,
  Users,
  Utensils,
  UtensilsCrossed,
  Volleyball,
  Wand2,
  Watch,
  Waves,
  Wrench,
  type LucideIcon,
} from "lucide-react";

/** Catálogo de ícones pro Calendário — compromissos das pessoas
 *  (esporte, música, escola, saúde etc.), separado de CATEGORY_ICON_OPTIONS
 *  (que é voltado a categorias financeiras). Mesmo formato {value, label,
 *  icon}, reaproveitado pelo componente IconPicker compartilhado. */
export const EVENT_ICON_OPTIONS: { value: string; label: string; icon: LucideIcon }[] = [
  // Esportes
  { value: "sport", label: "Esporte", icon: Trophy },
  { value: "gym", label: "Academia", icon: Dumbbell },
  { value: "bike", label: "Ciclismo", icon: Bike },
  { value: "run", label: "Corrida", icon: Footprints },
  { value: "swim", label: "Natação", icon: Waves },
  { value: "ball_sport", label: "Vôlei/Futebol", icon: Volleyball },
  { value: "sailing", label: "Vela/Náutica", icon: Sailboat },
  { value: "anchor", label: "Esporte aquático", icon: Anchor },
  { value: "medal", label: "Competição", icon: Medal },
  { value: "target", label: "Treino/Meta", icon: Target },
  { value: "mountain", label: "Trilha/Montanha", icon: Mountain },

  // Arte e música
  { value: "music", label: "Música", icon: Music },
  { value: "music_practice", label: "Ensaio musical", icon: Music2 },
  { value: "guitar", label: "Violão/Guitarra", icon: Guitar },
  { value: "piano", label: "Piano", icon: Piano },
  { value: "drums", label: "Bateria", icon: Drum },
  { value: "singing", label: "Canto", icon: Mic },
  { value: "dance", label: "Dança/Teatro", icon: Drama },
  { value: "theater", label: "Teatro/Peça", icon: Theater },
  { value: "art", label: "Arte", icon: Palette },
  { value: "painting", label: "Pintura", icon: Brush },
  { value: "craft", label: "Artesanato", icon: Wand2 },
  { value: "photo", label: "Fotografia", icon: Camera },
  { value: "movie", label: "Cinema", icon: Clapperboard },
  { value: "popcorn", label: "Sessão de filme", icon: Popcorn },

  // Escola e desenvolvimento
  { value: "school", label: "Escola", icon: School },
  { value: "graduation", label: "Formatura", icon: GraduationCap },
  { value: "homework", label: "Estudo/Lição", icon: BookOpen },
  { value: "backpack", label: "Aula/curso", icon: Backpack },
  { value: "library", label: "Biblioteca", icon: Library },
  { value: "science", label: "Ciências", icon: Microscope },
  { value: "math", label: "Matemática", icon: Calculator },
  { value: "writing", label: "Redação", icon: Pencil },
  { value: "puzzle", label: "Jogo educativo", icon: Puzzle },
  { value: "language", label: "Idiomas", icon: Globe },

  // Saúde
  { value: "medical", label: "Consulta médica", icon: Stethoscope },
  { value: "health", label: "Saúde", icon: HeartPulse },
  { value: "dentist", label: "Dentista", icon: Smile },
  { value: "vaccine", label: "Vacina/Exame", icon: Syringe },
  { value: "pharmacy", label: "Farmácia", icon: Pill },
  { value: "therapy", label: "Terapia", icon: HandHeart },
  { value: "wellness", label: "Bem-estar", icon: Heart },

  // Família e casa
  { value: "family", label: "Família", icon: Users },
  { value: "baby", label: "Bebê/Criança", icon: Baby },
  { value: "sleepover", label: "Dormir fora", icon: BedDouble },
  { value: "home_task", label: "Tarefa de casa", icon: Wrench },
  { value: "repair", label: "Manutenção", icon: Hammer },
  { value: "home", label: "Compromisso em casa", icon: Home },
  { value: "chores", label: "Organização", icon: Sparkles },
  { value: "church", label: "Religião/Igreja", icon: Church },
  { value: "person", label: "Pessoal", icon: PersonStanding },

  // Celebrações e social
  { value: "party", label: "Festa", icon: PartyPopper },
  { value: "birthday", label: "Aniversário", icon: Cake },
  { value: "gift", label: "Presente", icon: Gift },
  { value: "ticket", label: "Ingresso/Show", icon: Ticket },
  { value: "celebration", label: "Comemoração", icon: Crown },
  { value: "game_night", label: "Jogos de tabuleiro", icon: Dices },
  { value: "video_game", label: "Videogame", icon: Gamepad2 },

  // Alimentação
  { value: "food", label: "Refeição", icon: Utensils },
  { value: "restaurant", label: "Restaurante", icon: UtensilsCrossed },
  { value: "snack", label: "Lanche", icon: Croissant },
  { value: "dessert", label: "Sobremesa", icon: IceCreamCone },
  { value: "pizza", label: "Pizza", icon: Pizza },
  { value: "cooking", label: "Cozinhar", icon: Cookie },
  { value: "shopping", label: "Compras", icon: ShoppingBag },
  { value: "market", label: "Mercado", icon: ShoppingCart },

  // Viagem e ar livre
  { value: "travel", label: "Viagem", icon: Plane },
  { value: "road_trip", label: "Estrada", icon: Car },
  { value: "bus_trip", label: "Passeio de ônibus", icon: Bus },
  { value: "train_trip", label: "Trem", icon: Train },
  { value: "luggage", label: "Bagagem", icon: Luggage },
  { value: "camping", label: "Camping", icon: Tent },
  { value: "beach", label: "Praia", icon: Umbrella },
  { value: "park", label: "Parque", icon: Trees },
  { value: "nature", label: "Natureza", icon: Leaf },
  { value: "picnic", label: "Piquenique", icon: Flower2 },
  { value: "map", label: "Passeio/Local", icon: MapPin },
  { value: "explore", label: "Explorar", icon: Compass },
  { value: "sunrise", label: "Manhã cedo", icon: Sunrise },
  { value: "sun", label: "Ao ar livre", icon: Sun },
  { value: "night", label: "Noturno", icon: Moon },
  { value: "snow", label: "Inverno/Neve", icon: Snowflake },
  { value: "rocket", label: "Aventura", icon: Rocket },

  // Pets e animais
  { value: "pet", label: "Pet", icon: PawPrint },
  { value: "dog", label: "Cachorro", icon: Dog },
  { value: "cat", label: "Gato", icon: Cat },
  { value: "bird", label: "Pássaro", icon: Bird },
  { value: "fish", label: "Peixe/Aquário", icon: Fish },
  { value: "rabbit", label: "Coelho", icon: Rabbit },

  // Trabalho e finanças
  { value: "work", label: "Trabalho", icon: Briefcase },
  { value: "laptop", label: "Reunião online", icon: Laptop },
  { value: "documents", label: "Documentos", icon: Paperclip },
  { value: "finance", label: "Financeiro", icon: PiggyBank },
  { value: "landmark", label: "Banco/Cartório", icon: Landmark },

  // Diversos
  { value: "car_service", label: "Manutenção do carro", icon: Car },
  { value: "haircut", label: "Cabelo/Beleza", icon: Scissors },
  { value: "glasses", label: "Óculos", icon: Glasses },
  { value: "watch", label: "Horário fixo", icon: Watch },
  { value: "idea", label: "Ideia/Planejamento", icon: Lightbulb },
  { value: "flag", label: "Marco importante", icon: Flag },
  { value: "star", label: "Especial", icon: Star },
  { value: "flame", label: "Prioridade", icon: Flame },
  { value: "news", label: "Notícia/Aviso", icon: Newspaper },
  { value: "key", label: "Chaves/Acesso", icon: Key },
  { value: "palm", label: "Férias", icon: Palmtree },
  { value: "award", label: "Compromisso", icon: Award },
];

const ICON_BY_VALUE = new Map(EVENT_ICON_OPTIONS.map((option) => [option.value, option.icon]));

export function eventIconFor(icon: string | null | undefined): LucideIcon {
  if (icon && ICON_BY_VALUE.has(icon)) return ICON_BY_VALUE.get(icon)!;
  return Users;
}
