/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ReportsRouteImport } from './routes/reports'
import { Route as PlanejamentoRouteImport } from './routes/planejamento'
import { Route as LoginRouteImport } from './routes/login'
import { Route as LandingRouteImport } from './routes/landing'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as ConciliacaoRouteImport } from './routes/conciliacao'
import { Route as IndexRouteImport } from './routes/index'
import { Route as CadastrosMembrosRouteImport } from './routes/cadastros/membros'
import { Route as CadastrosContasECartoesRouteImport } from './routes/cadastros/contas-e-cartoes'
import { Route as CadastrosCategoriasRouteImport } from './routes/cadastros/categorias'

const ReportsRoute = ReportsRouteImport.update({
  id: '/reports',
  path: '/reports',
  getParentRoute: () => rootRouteImport,
} as any)
const PlanejamentoRoute = PlanejamentoRouteImport.update({
  id: '/planejamento',
  path: '/planejamento',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const LandingRoute = LandingRouteImport.update({
  id: '/landing',
  path: '/landing',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const ConciliacaoRoute = ConciliacaoRouteImport.update({
  id: '/conciliacao',
  path: '/conciliacao',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const CadastrosMembrosRoute = CadastrosMembrosRouteImport.update({
  id: '/cadastros/membros',
  path: '/cadastros/membros',
  getParentRoute: () => rootRouteImport,
} as any)
const CadastrosContasECartoesRoute = CadastrosContasECartoesRouteImport.update({
  id: '/cadastros/contas-e-cartoes',
  path: '/cadastros/contas-e-cartoes',
  getParentRoute: () => rootRouteImport,
} as any)
const CadastrosCategoriasRoute = CadastrosCategoriasRouteImport.update({
  id: '/cadastros/categorias',
  path: '/cadastros/categorias',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/conciliacao': typeof ConciliacaoRoute
  '/dashboard': typeof DashboardRoute
  '/landing': typeof LandingRoute
  '/login': typeof LoginRoute
  '/planejamento': typeof PlanejamentoRoute
  '/reports': typeof ReportsRoute
  '/cadastros/categorias': typeof CadastrosCategoriasRoute
  '/cadastros/contas-e-cartoes': typeof CadastrosContasECartoesRoute
  '/cadastros/membros': typeof CadastrosMembrosRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/conciliacao': typeof ConciliacaoRoute
  '/dashboard': typeof DashboardRoute
  '/landing': typeof LandingRoute
  '/login': typeof LoginRoute
  '/planejamento': typeof PlanejamentoRoute
  '/reports': typeof ReportsRoute
  '/cadastros/categorias': typeof CadastrosCategoriasRoute
  '/cadastros/contas-e-cartoes': typeof CadastrosContasECartoesRoute
  '/cadastros/membros': typeof CadastrosMembrosRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/conciliacao': typeof ConciliacaoRoute
  '/dashboard': typeof DashboardRoute
  '/landing': typeof LandingRoute
  '/login': typeof LoginRoute
  '/planejamento': typeof PlanejamentoRoute
  '/reports': typeof ReportsRoute
  '/cadastros/categorias': typeof CadastrosCategoriasRoute
  '/cadastros/contas-e-cartoes': typeof CadastrosContasECartoesRoute
  '/cadastros/membros': typeof CadastrosMembrosRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/conciliacao'
    | '/dashboard'
    | '/landing'
    | '/login'
    | '/planejamento'
    | '/reports'
    | '/cadastros/categorias'
    | '/cadastros/contas-e-cartoes'
    | '/cadastros/membros'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/conciliacao'
    | '/dashboard'
    | '/landing'
    | '/login'
    | '/planejamento'
    | '/reports'
    | '/cadastros/categorias'
    | '/cadastros/contas-e-cartoes'
    | '/cadastros/membros'
  id:
    | '__root__'
    | '/'
    | '/conciliacao'
    | '/dashboard'
    | '/landing'
    | '/login'
    | '/planejamento'
    | '/reports'
    | '/cadastros/categorias'
    | '/cadastros/contas-e-cartoes'
    | '/cadastros/membros'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ConciliacaoRoute: typeof ConciliacaoRoute
  DashboardRoute: typeof DashboardRoute
  LandingRoute: typeof LandingRoute
  LoginRoute: typeof LoginRoute
  PlanejamentoRoute: typeof PlanejamentoRoute
  ReportsRoute: typeof ReportsRoute
  CadastrosCategoriasRoute: typeof CadastrosCategoriasRoute
  CadastrosContasECartoesRoute: typeof CadastrosContasECartoesRoute
  CadastrosMembrosRoute: typeof CadastrosMembrosRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/reports': {
      id: '/reports'
      path: '/reports'
      fullPath: '/reports'
      preLoaderRoute: typeof ReportsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/planejamento': {
      id: '/planejamento'
      path: '/planejamento'
      fullPath: '/planejamento'
      preLoaderRoute: typeof PlanejamentoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/landing': {
      id: '/landing'
      path: '/landing'
      fullPath: '/landing'
      preLoaderRoute: typeof LandingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/conciliacao': {
      id: '/conciliacao'
      path: '/conciliacao'
      fullPath: '/conciliacao'
      preLoaderRoute: typeof ConciliacaoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cadastros/membros': {
      id: '/cadastros/membros'
      path: '/cadastros/membros'
      fullPath: '/cadastros/membros'
      preLoaderRoute: typeof CadastrosMembrosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cadastros/contas-e-cartoes': {
      id: '/cadastros/contas-e-cartoes'
      path: '/cadastros/contas-e-cartoes'
      fullPath: '/cadastros/contas-e-cartoes'
      preLoaderRoute: typeof CadastrosContasECartoesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cadastros/categorias': {
      id: '/cadastros/categorias'
      path: '/cadastros/categorias'
      fullPath: '/cadastros/categorias'
      preLoaderRoute: typeof CadastrosCategoriasRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ConciliacaoRoute: ConciliacaoRoute,
  DashboardRoute: DashboardRoute,
  LandingRoute: LandingRoute,
  LoginRoute: LoginRoute,
  PlanejamentoRoute: PlanejamentoRoute,
  ReportsRoute: ReportsRoute,
  CadastrosCategoriasRoute: CadastrosCategoriasRoute,
  CadastrosContasECartoesRoute: CadastrosContasECartoesRoute,
  CadastrosMembrosRoute: CadastrosMembrosRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
